- name: Remove old config backups
  hosts: all
  gather_facts: false
  tasks:
    - name: Go over each config dir and remove backups
      shell: "find {{item}} -type f -name '*~' -mtime +7|xargs -n 1023 -r rm"
      with_items:
        - /etc
        - /usr/local/etc
